=== xmlBlaster-org/xmlBlaster/xmlBlaster/testsuite/data/xml/marcel.dtd
<!ELEMENT xmlBlaster (key+)>
<!ELEMENT key (Airport)>
<!ELEMENT Airport (Runway)>
<!ELEMENT Runway (WindVeloc)>
<!ELEMENT WindVeloc (#PCDATA)>
 
<!ATTLIST key oid ID #IMPLIED>
<!ATTLIST Airport icao ID #IMPLIED>
<!ATTLIST Runway id ID #IMPLIED> 
<!ATTLIST WindVeloc w_id ID #IMPLIED>

=== xmlBlaster-org/xmlBlaster/xmlBlaster/testsuite/data/xml/marcel.xml
<?xml version="1.0"?>
<!DOCTYPE xmlBlaster SYSTEM "marcel.dtd">
<!-- So liegen die keys im xmlBlaster DOM Baum -->
<xmlBlaster>
   <key oid="Wasschoenes">
      <Airport icao="EDDI">
        <Runway id="d1">
           <WindVeloc w_id="xyz">HALLO</WindVeloc>
        </Runway>
      </Airport>
   </key>

   <key oid="Whoenes">
      <Airport icao="EDDN">
        <Runway id="d3">
           <WindVeloc w_id="_i">HLO</WindVeloc>
        </Runway>
      </Airport>
   </key>

</xmlBlaster>
