=== xmlBlaster-org/xmlBlaster/xmlBlaster/doc/requirements/requirement.dtd
<?xml version='1.0' encoding='ISO-8859-1' ?>

<!ELEMENT requirement (
	topic,
	description,
	author,
	date,
	revision,
	fix*
	)>

<!ENTITY % text "#PCDATA">

<!ELEMENT topic  (%text;)>
<!ELEMENT description  (%text;)> 
<!ELEMENT author  (%text;)> 
<!ELEMENT date  (%text;)> 
<!ELEMENT revision  (%text;)> 

<!ELEMENT fix (
	name,
	comment,
	status,
	test
	)>

<!ELEMENT name  (%text;)> 
<!ELEMENT comment  (%text;)> 
<!ELEMENT status  (%text;)> 
<!ELEMENT test  (%text;)> 

<!ATTLIST requirement
          id ID #REQUIRED
			 prio  (LOW | MEDIUM | HIGH) "LOW"
          type (NEW | BUG) "BUG">
<!ATTLIST test tool (SUITE | MANUAL) "SUITE">

=== xmlBlaster-org/xmlBlaster/xmlBlaster/doc/requirements/engine.qos.destination.offline.xml
<?xml version='1.0' encoding='ISO-8859-1' ?>
<!DOCTYPE requirement SYSTEM "requirement.dtd">

<requirement id='engine.qos.destination.offline' type='NEW' prio='LOW' status="CLOSED">
   <topic>If the receiver of a PtP message is offline or has no callback, the sender gets an exception</topic>
   <description>
      If you send a message to a named destination, using the qos &lt;destination&lt; tag,
      and there is no callback for this receiver, or the receiver is not logged in
      and the &lt;ForceUpdate&lt; qos tag is not set in this message, you get a
      XmlBlasterException.
   </description>
   <see>engine.qos.publish.ForceQueuing</see>
   <author>ruff@swand.lake.de</author>
   <date>2000 03 17</date>
   <revision>$Revision: 1.1 $</revision>
   <fix status="CLOSED">
      <name>-</name>
      <comment>-</comment>
      <test tool="SUITE">testsuite.org.xmlBlaster.TestPtDQueue</test>
   </fix>
</requirement>

=== xmlBlaster-org/xmlBlaster/xmlBlaster/doc/requirements/engine.replication.xml
<?xml version='1.0' encoding='ISO-8859-1' ?>
<!DOCTYPE requirement SYSTEM "requirement.dtd">

<requirement id='engine.replication' type='NEW' prio='LOW' status="OPEN">
   <topic>XmlBlaster provides a replication mechanism following the master/slave ticket paradigm</topic>
   <description>
      If multiple xmlBlaster servers are running, every message is assigned to exactly one
      master server. The different xmlBlaster servers login to each other like other clients
      and act as slave to messages which they are not master from.
      This login is done in 'lazy' mode. As soon as a client requests a message
      for which the local server is not master, this server does a login to the master
      and subscribes the message from there. The message is than cached locally and further
      local requests from clients are handled locally.
      An adjustable expire date clears the cached message.
      If a message is published from a data source to a slave server, the message is routed directly
      to the master server. If the master server is currently offline, it is queued
      for this 'client' until it logs in.
   </description>
   <author>ruff@swand.lake.de</author>
   <date>2000 04 03</date>
   <revision>$Revision: 1.1 $</revision>
   <testcase status="OPEN">
      <name>-</name>
      <comment>-</comment>
      <test tool="SUITE"></test>
   </testcase>
</requirement>

=== xmlBlaster-org/xmlBlaster/xmlBlaster/doc/requirements/util.property.xml
<?xml version='1.0' encoding='ISO-8859-1' ?>
<!DOCTYPE requirement SYSTEM "requirement.dtd">

<requirement id='util.property' type='NEW' prio='LOW' status="CLOSED">
   <topic>XmlBlaster provides a property file to allow a simple configuration</topic>
   <description>
      The xmlBlaster.properties file allows to customize the behavior of xmlBlaster.
      It is searched in the following locations:
      &lt;ol>
      &lt;li>In $HOME&lt;/li>
      &lt;li>In $XMLBLASTER_HOME&lt;/li>
      &lt;li>Local directory&lt;/li>
      &lt;li>Fallback: \xmlBlaster oder /usr/local/xmlBlaster&lt;/li>
      &lt;/ol>
   </description>
   <author>ruff@swand.lake.de</author>
   <date>2000 02 24</date>
   <revision>$Revision: 1.3 $</revision>
   <testcase status="CLOSED">
      <name>ruff@swand.lake.de</name>
      <comment>
      The property file is used everywhere in the xmlBlaster code.
      The modules test their property variables in their own test cases.
      </comment>
      <test tool="SUITE">testsuite.org.xmlBlaster.TestAll</test>
   </testcase>
</requirement>

=== xmlBlaster-org/xmlBlaster/xmlBlaster/doc/requirements/util.recorder.returnvalues.xml
<?xml version='1.0' encoding='ISO-8859-1' ?>
<!DOCTYPE requirement SYSTEM "requirement.dtd">

<requirement id='util.recorder.returnvalues' type='NEW' prio='LOW' status="CLOSED">
   <topic>The InvocationRecorder should allow to record the return values of method invocations as well</topic>
   <description>
      The current approach has the following drawback:
      The return values of the calls are lost.
      As soon as someone needs this, she should hack and extend
      the framework.
   </description>
   <author>ruff@swand.lake.de</author>
   <date>2000 02 24</date>
   <revision>$Revision: 1.3 $</revision>
   <testcase status="OPEN">
      <name></name>
      <comment>
      </comment>
      <test tool="SUITE"></test>
   </testcase>
</requirement>
